version: "3.4"

services:
  onlyoffice-connector:
    build:
      context: .
      dockerfile: docker/onlyoffice-connector/Dockerfile
    restart: unless-stopped
    environment:
      - SERVER_PORT=5000
      - SERVER_PREFIX=/plugins/onlyoffice/
      - CREDENTIALS_ENDPOINT=http://tdrive_node:4000/
      - ONLY_OFFICE_SERVER=http://onlyoffice:80/
      - CREDENTIALS_ID=tdrive_onlyoffice
      - CREDENTIALS_SECRET=apisecret
      - SERVER_ORIGIN=http://onlyoffice-connector:5000
    ports:
      - 5000:5000
    networks:
      - tdrive_network

networks:
  tdrive_network:
    name: tdrive_tdrive_network
    external: true
